import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css';

export default function Home() {
    const router = useRouter();

    return (
        <>
            <Head>
                <title>Monzo Clone</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className={styles.container}>
                <div>
                    <ul>
                        <li
                            className={styles.link}
                            onClick={() => router.push('/current-account')}
                        >
                            go to <b>Monzo Current Accounts</b> page
                        </li>
                    </ul>
                </div>
            </main>
        </>
    );
}
